from __future__ import print_function
import io
import os.path
from google.auth.transport.requests import Request
from google.oauth2.credentials import Credentials
from google_auth_oauthlib.flow import InstalledAppFlow
from googleapiclient.discovery import build
from googleapiclient.errors import HttpError
from googleapiclient.http import MediaIoBaseDownload

hymndic = {
    "1": "https://www.youtube.com/watch?v=FDpludwY46U",
    "2": "https://www.youtube.com/watch?v=u4c66cbU9-c",
    "3": "https://www.youtube.com/watch?v=BpMD-UziYbc",
    "4": "https://www.youtube.com/watch?v=hfH_dQpEMhk",
    "5": "https://www.youtube.com/watch?v=e6r1kYZJ1hg",
    "6": "https://www.youtube.com/watch?v=gUX4rONKdeI",
    "7": "https://www.youtube.com/watch?v=jRo9W3iHhLc",
    "8": "https://www.youtube.com/watch?v=W0Ha0nqpVtY",
    "9": "https://www.youtube.com/watch?v=d-Jm5BqIHms",
    "10": "https://www.youtube.com/watch?v=XafjwXQ7OF8",
    "11": "https://www.youtube.com/watch?v=7UlUMa8dlBg",
    "12": "https://www.youtube.com/watch?v=2WLfNPD0uhw",
    "13": "https://www.youtube.com/watch?v=xAzZsKdefi0",
    "14": "https://www.youtube.com/watch?v=KARmqJz3Ktg",
    "15": "https://www.youtube.com/watch?v=lVBzxAcXTVk",
    "16": "https://www.youtube.com/watch?v=724USSpz4ls",
    "17": "https://www.youtube.com/watch?v=1fkhW76iKSs",
    "18": "https://www.youtube.com/watch?v=5Zm_BUpeWHI",
    "19": "https://www.youtube.com/watch?v=MnBH-e_BpZQ",
    "20": "https://www.youtube.com/watch?v=4C23Lx1lwso",
    "21": "https://www.youtube.com/watch?v=BjHv6tOnhn0",
    "22": "https://www.youtube.com/watch?v=BwISjJU028U",
    "23": "https://www.youtube.com/watch?v=0LeRHv_eCgk",
    "24": "https://www.youtube.com/watch?v=AlTWVhSsndI",
    "25": "https://www.youtube.com/watch?v=T5jU2aXD0cI",
    "26": "https://www.youtube.com/watch?v=qQuZ30_VVbU",
    "27": "https://www.youtube.com/watch?v=xlkwuGo10Os",
    "28": "https://www.youtube.com/watch?v=DRYgNLQNjmU",
    "29": "https://www.youtube.com/watch?v=rDqhjaMUu8I",
    "30": "https://www.youtube.com/watch?v=SvLmewB4-tc",
    "31": "https://www.youtube.com/watch?v=LL5Pak4zcuA",
    "32": "https://www.youtube.com/watch?v=pnjg15RB6f8",
    "33": "https://www.youtube.com/watch?v=8hKR6ohrexE",
    "34": "https://www.youtube.com/watch?v=i_1znegpxLI",
    "35": "https://www.youtube.com/watch?v=KAu7WO38klQ",
    "36": "https://www.youtube.com/watch?v=h2zY2yqEhH8",
    "37": "https://www.youtube.com/watch?v=PRVP3fMMOJ8",
    "38": "https://www.youtube.com/watch?v=Sju2hLQ6hKU",
    "39": "https://www.youtube.com/watch?v=aARgwr11kt4",
    "40": "https://www.youtube.com/watch?v=AEIOZHynZ10",
    "41": "https://www.youtube.com/watch?v=BaJF1Tg3CJM",
    "42": "https://www.youtube.com/watch?v=GHr5fUzMD-8",
    "43": "https://www.youtube.com/watch?v=q7ckGf7nsU4",
    "44": "https://www.youtube.com/watch?v=niiUqUc9j1s",
    "45": "https://www.youtube.com/watch?v=zoxr6xrtoa8",
    "46": "https://www.youtube.com/watch?v=Vwpc1inHrwA",
    "47": "https://www.youtube.com/watch?v=5pCbe4IUoSQ",
    "48": "https://www.youtube.com/watch?v=dq4XfQZJrbg",
    "49": "https://www.youtube.com/watch?v=YiYxrq_0LuI",
    "50": "https://www.youtube.com/watch?v=s8iTxsqiiqM",
    "51": "https://www.youtube.com/watch?v=k-O7d-lvwtE",
    "52": "https://www.youtube.com/watch?v=ZKGM3HzpOZo",
    "53": "https://www.youtube.com/watch?v=hNdx9bWb_0s",
    "54": "https://www.youtube.com/watch?v=2rH9XgY6SGQ",
    "55": "https://www.youtube.com/watch?v=L81Mjny13d4",
    "56": "https://www.youtube.com/watch?v=5-PCVhz6uzg",
    "57": "https://www.youtube.com/watch?v=86bzYwgHtG4",
    "58": "https://www.youtube.com/watch?v=uNq843-YAvo",
    "59": "https://www.youtube.com/watch?v=ogxYKQWtuCo",
    "60": "https://www.youtube.com/watch?v=2khAUPUJ5VM",
    "61": "https://www.youtube.com/watch?v=EUHb7-depCY",
    "62": "https://www.youtube.com/watch?v=gwi_gzBwl98",
    "63": "https://www.youtube.com/watch?v=xopoI-il52Y",
    "64": "https://www.youtube.com/watch?v=Dh24lTXOorc",
    "65": "https://www.youtube.com/watch?v=38nr_ig4oYk",
    "66": "https://www.youtube.com/watch?v=1XYJWYHuZdg",
    "67": "https://www.youtube.com/watch?v=IN0WMRcnYq4",
    "68": "https://www.youtube.com/watch?v=98rSocNlrtw",
    "69": "https://www.youtube.com/watch?v=4XkYx2_xuPA",
    "70": "https://www.youtube.com/watch?v=vs4fs-zc66M",
    "71": "https://www.youtube.com/watch?v=wQFi-aVjuo0",
    "72": "https://www.youtube.com/watch?v=0QqmaJAVCss",
    "73": "https://www.youtube.com/watch?v=r130BsOP1Cs",
    "74": "https://www.youtube.com/watch?v=pDF_yaObO8M",
    "75": "https://www.youtube.com/watch?v=1k3ayNZz8jQ",
    "76": "https://www.youtube.com/watch?v=-0M7gBeQI78",
    "77": "https://www.youtube.com/watch?v=3-mP_nKu8yQ",
    "78": "https://www.youtube.com/watch?v=JzD8Fe1ICcw",
    "79": "https://www.youtube.com/watch?v=EbHIw7hpduI",
    "80": "https://www.youtube.com/watch?v=j_LfpCFhM1o",
    "81": "https://www.youtube.com/watch?v=kkHG9hyVZFI",
    "82": "https://www.youtube.com/watch?v=RDNxaHfPnLE",
    "83": "https://www.youtube.com/watch?v=j3eoiJdeg9k",
    "84": "https://www.youtube.com/watch?v=eNDUTp27XrI",
    "85": "https://www.youtube.com/watch?v=C3cAaEQRlSg",
    "86": "https://www.youtube.com/watch?v=G4KswVUWNM8",
    "87": "https://www.youtube.com/watch?v=GVg5Enb5OU4",
    "88": "https://www.youtube.com/watch?v=HXHaY7MkNoI",
    "89": "https://www.youtube.com/watch?v=02SEzuF8Yeg",
    "90": "https://www.youtube.com/watch?v=UiF50HoVxmQ",
    "91": "https://www.youtube.com/watch?v=manYe2ql8Kg",
    "92": "https://www.youtube.com/watch?v=neN3QmMPIf4",
    "93": "https://www.youtube.com/watch?v=Lp2_WQaM8KQ",
    "94": "https://www.youtube.com/watch?v=jgwICRa17Ts",
    "95": "https://www.youtube.com/watch?v=Pwa7fRMbURU",
    "96": "https://www.youtube.com/watch?v=qJXgvVGefyc",
    "97": "https://www.youtube.com/watch?v=KXB43Rs8SyU",
    "98": "https://www.youtube.com/watch?v=pcShGyOHlig",
    "99": "https://www.youtube.com/watch?v=nkGGdNovUXg",
    "100": "https://www.youtube.com/watch?v=LgbciTZ1VwM",
    "101": "https://www.youtube.com/watch?v=yey65PRKnwY",
    "102": "https://www.youtube.com/watch?v=xXSfV9DBfuU",
    "103": "https://www.youtube.com/watch?v=uARK7ATNd94",
    "104": "https://www.youtube.com/watch?v=6dOjCNKG3H8",
    "105": "https://www.youtube.com/watch?v=HRIFTOPGfQo",
    "106": "https://www.youtube.com/watch?v=PjPkdT0RdVg",
    "107": "https://www.youtube.com/watch?v=1LBGWEG23uc",
    "108": "https://www.youtube.com/watch?v=LYPwUpwFqJU",
    "109": "https://www.youtube.com/watch?v=xoUiEda5iJM",
    "110": "https://www.youtube.com/watch?v=RRpKJGGwcXE",
    "111": "https://www.youtube.com/watch?v=2wRdBPHruHU",
    "112": "https://www.youtube.com/watch?v=QvcJtKyiJaQ",
    "113": "https://www.youtube.com/watch?v=5EB_afTMfPc",
    "114": "https://www.youtube.com/watch?v=Jxim-KyuzMw",
    "115": "https://www.youtube.com/watch?v=3uF79G1Wwjw",
    "116": "https://www.youtube.com/watch?v=Kfplvg2IX6w",
    "117": "https://www.youtube.com/watch?v=kQbEAjwxHXU",
    "118": "https://www.youtube.com/watch?v=p0HlgYN5D6Q",
    "119": "https://www.youtube.com/watch?v=cS1Nl3pkS6g",
    "120": "https://www.youtube.com/watch?v=pb6P7_xmUQs",
    "121": "https://www.youtube.com/watch?v=1d_Sj5oJk2k",
    "122": "https://www.youtube.com/watch?v=zJqNjxb-7SI",
    "123": "https://www.youtube.com/watch?v=IMJRhe3K1EA",
    "124": "https://www.youtube.com/watch?v=VlxR27Iy9LQ",
    "125": "https://www.youtube.com/watch?v=t0ehkXbVZvw",
    "126": "https://www.youtube.com/watch?v=1SBM9-TndOU",
    "127": "https://www.youtube.com/watch?v=DMdabK3IbAU",
    "128": "https://www.youtube.com/watch?v=FHqRzJ1Pj0Q",
    "129": "https://www.youtube.com/watch?v=R3J8A4uVooQ",
    "130": "https://www.youtube.com/watch?v=KeUClZbg8Uk",
    "131": "https://www.youtube.com/watch?v=U1MtpuMnAK8",
    "132": "https://www.youtube.com/watch?v=WLANtS8injM",
    "133": "https://www.youtube.com/watch?v=1kM5QluWwqc",
    "134": "https://www.youtube.com/watch?v=hXrjWCkDmpY",
    "135": "https://www.youtube.com/watch?v=f9VL-sdtUHg",
    "136": "https://www.youtube.com/watch?v=20XieWKvvvA",
    "137": "https://www.youtube.com/watch?v=m2XiTAFMXJ0",
    "138": "https://www.youtube.com/watch?v=NTBQm-5nTZ0",
    "139": "https://www.youtube.com/watch?v=9SHy1_R9Rx4",
    "140": "https://www.youtube.com/watch?v=80eW16boEDg",
    "141": "https://www.youtube.com/watch?v=0xi3zUDft6g",
    "142": "https://www.youtube.com/watch?v=QbgZAOmi0lc",
    "143": "https://www.youtube.com/watch?v=Jxr4l1rb47Q",
    "144": "https://www.youtube.com/watch?v=ENC3wRLqSWY",
    "145": "https://www.youtube.com/watch?v=BAVvAtp5I7M",
    "146": "https://www.youtube.com/watch?v=Cp1MchLAT4Q",
    "147": "https://www.youtube.com/watch?v=Lw5boxvR22k",
    "148": "https://www.youtube.com/watch?v=gmYPdCt9IlM",
    "149": "https://www.youtube.com/watch?v=yi08qQYUizE",
    "150": "https://www.youtube.com/watch?v=H6uJzMKrSF8",
    "151": "https://www.youtube.com/watch?v=J-LrXdce3BQ",
    "152": "https://www.youtube.com/watch?v=PugB4piaHHo",
    "153": "https://www.youtube.com/watch?v=Qc_6UoL0Y2g",
    "154": "https://www.youtube.com/watch?v=E1wkziOywHE",
    "155": "https://www.youtube.com/watch?v=RZ7z3wlZ6w0",
    "156": "https://www.youtube.com/watch?v=Tse3sRoZjUY",
    "157": "https://www.youtube.com/watch?v=xf46ZtpsWFU",
    "158": "https://www.youtube.com/watch?v=3bsZ_hMpaG8",
    "159": "https://www.youtube.com/watch?v=OZHToenZk6k",
    "160": "https://www.youtube.com/watch?v=UFgPVxywUzk",
    "161": "https://www.youtube.com/watch?v=d2TGxq6cUdc",
    "162": "https://www.youtube.com/watch?v=lNnC4Lj998s",
    "163": "https://www.youtube.com/watch?v=_G5qqB7zbx4",
    "164": "https://www.youtube.com/watch?v=6_dlUP46mEQ",
    "165": "https://www.youtube.com/watch?v=X4VP_cLQCSY",
    "166": "https://www.youtube.com/watch?v=h7uQpNUh9Cw",
    "167": "https://www.youtube.com/watch?v=ajWDH9CUcXU",
    "168": "https://www.youtube.com/watch?v=tsPbzFTxyD8",
    "169": "https://www.youtube.com/watch?v=Dyd6mAe1LoI",
    "170": "https://www.youtube.com/watch?v=ZdBnuWtqR0c",
    "171": "https://www.youtube.com/watch?v=OvOiXTDTiIk",
    "172": "https://www.youtube.com/watch?v=qY07MGsAkZ0",
    "173": "https://www.youtube.com/watch?v=1AaW6xXABWM",
    "174": "https://www.youtube.com/watch?v=AbkpBk1b3Rc",
    "175": "https://www.youtube.com/watch?v=7SuzQVHTvb8",
    "176": "https://www.youtube.com/watch?v=UM42XBG0EoY",
    "177": "https://www.youtube.com/watch?v=fwvoO_TPhwY",
    "178": "https://www.youtube.com/watch?v=WHCMQjeWqVs",
    "179": "https://www.youtube.com/watch?v=tA4BbhaEKeA",
    "180": "https://www.youtube.com/watch?v=WBXKUyPkNqo",
    "181": "https://www.youtube.com/watch?v=Ti-3MEfiTHQ",
    "182": "https://www.youtube.com/watch?v=ubclOJpcEgc",
    "183": "https://www.youtube.com/watch?v=1JIetpF0Ihk",
    "184": "https://www.youtube.com/watch?v=z3FtUwqdEU4",
    "185": "https://www.youtube.com/watch?v=RvM8AvWDnSQ",
    "186": "https://www.youtube.com/watch?v=Qqp1ZZi1wSw",
    "187": "https://www.youtube.com/watch?v=485b67iCENY",
    "188": "https://www.youtube.com/watch?v=cRUWUT-jwYc",
    "189": "https://www.youtube.com/watch?v=EHbbpkoLJ5U",
    "190": "https://www.youtube.com/watch?v=NxdttzyFf2o",
    "191": "https://www.youtube.com/watch?v=TZnLhvVG68Y",
    "192": "https://www.youtube.com/watch?v=HUY6sJkScBQ",
    "193": "https://www.youtube.com/watch?v=pheGcnEq8p8",
    "194": "https://www.youtube.com/watch?v=UabnP6pgbTc",
    "195": "https://www.youtube.com/watch?v=A4izEhw2FLE",
    "196": "https://www.youtube.com/watch?v=Dsy2ouhHzIs",
    "197": "https://www.youtube.com/watch?v=Xmna0YjSQ-s",
    "198": "https://www.youtube.com/watch?v=J0dZy3WKJCc",
    "199": "https://www.youtube.com/watch?v=V6AW8M1Jg-0",
    "200": "https://www.youtube.com/watch?v=V37Xhq3pVj8",
    "201": "https://www.youtube.com/watch?v=kUuN3BnJnaI",
    "202": "https://www.youtube.com/watch?v=kQWEGODrfKc",
    "203": "https://www.youtube.com/watch?v=TqplFQwwgGM",
    "204": "https://www.youtube.com/watch?v=llDMZ7vVsQU",
    "205": "https://www.youtube.com/watch?v=x097Y9HQpL4",
    "206": "https://www.youtube.com/watch?v=aWL-qItB_uY",
    "207": "https://www.youtube.com/watch?v=t9Pp34pZ1AQ",
    "208": "https://www.youtube.com/watch?v=u_D5Tk3qn1Y",
    "209": "https://www.youtube.com/watch?v=ZTX7-BadhSc",
    "210": "https://www.youtube.com/watch?v=3axUf7ybwqA",
    "211": "https://www.youtube.com/watch?v=vBfU_89IE44",
    "212": "https://www.youtube.com/watch?v=6NYekrMlTQY",
    "213": "https://www.youtube.com/watch?v=ILnsDgw5E30",
    "214": "https://www.youtube.com/watch?v=RylJ4GK3r0k",
    "215": "https://www.youtube.com/watch?v=dhYaXaT7SBQ",
    "216": "https://www.youtube.com/watch?v=OAjs3XGoNS8",
    "217": "https://www.youtube.com/watch?v=BCeuEXUiNas",
    "218": "https://www.youtube.com/watch?v=yF9207i7eQQ",
    "219": "https://www.youtube.com/watch?v=S8Xd30MZcNY",
    "220": "https://www.youtube.com/watch?v=ddnROB-Iagk",
    "221": "https://www.youtube.com/watch?v=Gd-0ohdm-PI",
    "222": "https://www.youtube.com/watch?v=ttA_S0UZpCI",
    "223": "https://www.youtube.com/watch?v=cWZK-r9LP2I",
    "224": "https://www.youtube.com/watch?v=bENSL9Ox2LU",
    "225": "https://www.youtube.com/watch?v=6VG21tjg0bM",
    "226": "https://www.youtube.com/watch?v=DcKQcVY394U",
    "227": "https://www.youtube.com/watch?v=IfM3j1Zbkh0",
    "228": "https://www.youtube.com/watch?v=ZzFbbopH8Vo",
    "229": "https://www.youtube.com/watch?v=oE4qRzuFjk4",
    "230": "https://www.youtube.com/watch?v=Sv1Mk5f8Gm4",
    "231": "https://www.youtube.com/watch?v=NWbx4RI3mAg",
    "232": "https://www.youtube.com/watch?v=PNeCs4J9jfE",
    "233": "https://www.youtube.com/watch?v=s8nEm0RjysI",
    "234": "https://www.youtube.com/watch?v=6T8ajgIR4Mk",
    "235": "https://www.youtube.com/watch?v=6gOhEHoEcGA",
    "236": "https://www.youtube.com/watch?v=qAu0J5_yhqg",
    "237": "https://www.youtube.com/watch?v=fI_xWfXjWcg",
    "238": "https://www.youtube.com/watch?v=SEEy-WPicdc",
    "239": "https://www.youtube.com/watch?v=irEOEYk8ZkI",
    "240": "https://www.youtube.com/watch?v=Rv0F4c4C-Wg",
    "241": "https://www.youtube.com/watch?v=tSDeT4aYMlY",
    "242": "https://www.youtube.com/watch?v=olcB1p-umdQ",
    "243": "https://www.youtube.com/watch?v=ZHK2rdtAjTs",
    "244": "https://www.youtube.com/watch?v=Q1aD3qdatVI",
    "245": "https://www.youtube.com/watch?v=ZrnPn--2-C0",
    "246": "https://www.youtube.com/watch?v=blOjsarznsQ",
    "247": "https://www.youtube.com/watch?v=LCRzBt65wQA",
    "248": "https://www.youtube.com/watch?v=zpfmhV1bkS8",
    "249": "https://www.youtube.com/watch?v=RGvKiqTibOc",
    "250": "https://www.youtube.com/watch?v=AH39bafXKrE",
    "251": "https://www.youtube.com/watch?v=ZHzaGAfdoCM",
    "252": "https://www.youtube.com/watch?v=BvKZVC9cK9Q",
    "253": "https://www.youtube.com/watch?v=7Ci4QNv-pKA",
    "254": "https://www.youtube.com/watch?v=VxOMU2J_ZAI",
    "255": "https://www.youtube.com/watch?v=vf3jfoQFP3U",
    "256": "https://www.youtube.com/watch?v=DEIsgr6rAXU",
    "257": "https://www.youtube.com/watch?v=LSLQ7w4we1M",
    "258": "https://www.youtube.com/watch?v=VbPvb63MO7E",
    "259": "https://www.youtube.com/watch?v=nWIsUdDHHmc",
    "260": "https://www.youtube.com/watch?v=c4JUrBiNjas",
    "261": "https://www.youtube.com/watch?v=OOCiWJTMvkI",
    "262": "https://www.youtube.com/watch?v=PEUoGbpsQo4",
    "263": "https://www.youtube.com/watch?v=eC_SG8HxQ_4",
    "264": "https://www.youtube.com/watch?v=MGgZCcpZIYE",
    "265": "https://www.youtube.com/watch?v=MTnD-Y7pjZA",
    "266": "https://www.youtube.com/watch?v=Wdz8uN0DPFY",
    "267": "https://www.youtube.com/watch?v=qShdC3CEHN0",
    "268": "https://www.youtube.com/watch?v=maPqiR2yjy0",
    "269": "https://www.youtube.com/watch?v=ROWbiKrX-1U",
    "270": "https://www.youtube.com/watch?v=tLhObj3zj-c",
    "271": "https://www.youtube.com/watch?v=Kr-tDldyFmQ",
    "272": "https://www.youtube.com/watch?v=c9f7n3Ro6_Y",
    "273": "https://www.youtube.com/watch?v=cgNzy67c04E",
    "274": "https://www.youtube.com/watch?v=XdXaEhP6LjU",
    "275": "https://www.youtube.com/watch?v=As-X-j6HRdE",
    "276": "https://www.youtube.com/watch?v=0v1ihqB0gpI",
    "277": "https://www.youtube.com/watch?v=r9KpN18SQDg",
    "278": "https://www.youtube.com/watch?v=sXZgMQKfLfk",
    "279": "https://www.youtube.com/watch?v=7XEXWM9JX0E",
    "280": "https://www.youtube.com/watch?v=O4pIdHTqSlM",
    "281": "https://www.youtube.com/watch?v=4B2i8A9v4qc",
    "282": "https://www.youtube.com/watch?v=64erEGHX6tg",
    "283": "https://www.youtube.com/watch?v=lXpmeNNeztI",
    "284": "https://www.youtube.com/watch?v=UBzEdvwvAQY",
    "285": "https://www.youtube.com/watch?v=qNqAq54JUxg",
    "286": "https://www.youtube.com/watch?v=179Ih-iPnk0",
    "287": "https://www.youtube.com/watch?v=qkiZ-pjlcqs",
    "288": "https://www.youtube.com/watch?v=ndQK0QjLHlU",
    "289": "https://www.youtube.com/watch?v=DnJh2Iu9_4Y",
    "290": "https://www.youtube.com/watch?v=EhZFepZ47yY",
    "291": "https://www.youtube.com/watch?v=rHs4oa1_D9Q",
    "292": "https://www.youtube.com/watch?v=_EJR05GlhLQ",
    "293": "https://www.youtube.com/watch?v=V7Qx617dQQU",
    "294": "https://www.youtube.com/watch?v=5w3Xrdf5i_0",
    "295": "https://www.youtube.com/watch?v=5BB1MAN3g1I",
    "296": "https://www.youtube.com/watch?v=JGnzZ3eY5Xg",
    "297": "https://www.youtube.com/watch?v=25cPKkUP8go",
    "298": "https://www.youtube.com/watch?v=diMJD80zr30",
    "299": "https://www.youtube.com/watch?v=2jlp0c_gOck",
    "300": "https://www.youtube.com/watch?v=HZxnyB3lJ-k",
    "301": "https://www.youtube.com/watch?v=X6AAFwBkfEM",
    "302": "https://www.youtube.com/watch?v=bzXmFmM4CTM",
    "303": "https://www.youtube.com/watch?v=FlkCgkhQ5CI",
    "304": "https://www.youtube.com/watch?v=wAW5aQOksIg",
    "305": "https://www.youtube.com/watch?v=nYohbTMsyfo",
    "306": "https://www.youtube.com/watch?v=hwSVlpmYTWM",
    "307": "https://www.youtube.com/watch?v=ai_AQ1CwA2A",
    "308": "https://www.youtube.com/watch?v=lCz31f0wvvI",
    "309": "https://www.youtube.com/watch?v=J-JW7ALhif8",
    "310": "https://www.youtube.com/watch?v=vylQz82zkKE",
    "311": "https://www.youtube.com/watch?v=CVC5EOg8pCM",
    "312": "https://www.youtube.com/watch?v=g9B7YsUgUNM",
    "313": "https://www.youtube.com/watch?v=pI6-8Jet0YU",
    "314": "https://www.youtube.com/watch?v=TlArU2RQ2YY",
    "315": "https://www.youtube.com/watch?v=jBfNNgtMVUA",
    "316": "https://www.youtube.com/watch?v=5RRcpOBlXeA",
    "317": "https://www.youtube.com/watch?v=_8yIJOzF0rw",
    "318": "https://www.youtube.com/watch?v=hrtXSRc5Ces",
    "319": "https://www.youtube.com/watch?v=s99navSSdWM",
    "320": "https://www.youtube.com/watch?v=Wl9Xe0a1WRI",
    "321": "https://www.youtube.com/watch?v=4OR2dSNYuXk",
    "322": "https://www.youtube.com/watch?v=WmkAm7Eog80",
    "323": "https://www.youtube.com/watch?v=ti8OJHZqvUs",
    "324": "https://www.youtube.com/watch?v=VyKaiFCoIXA",
    "325": "https://www.youtube.com/watch?v=v76WHJ132HI",
    "326": "https://www.youtube.com/watch?v=CsPuhdOn8ko",
    "327": "https://www.youtube.com/watch?v=1ibGBe9svTw",
    "328": "https://www.youtube.com/watch?v=AW5sH1Z4XYs",
    "329": "https://www.youtube.com/watch?v=0SoM9vhYIwc",
    "330": "https://www.youtube.com/watch?v=mQblvleLL40",
    "331": "https://www.youtube.com/watch?v=ol-pFzHphIQ",
    "332": "https://www.youtube.com/watch?v=1dA0FMuuftU",
    "333": "https://www.youtube.com/watch?v=MeeNmIEjLVs",
    "334": "https://www.youtube.com/watch?v=JCYBqVqtKGQ",
    "335": "https://www.youtube.com/watch?v=WOpYIxGYvK0",
    "336": "https://www.youtube.com/watch?v=2QuelXhYD8w",
    "337": "https://www.youtube.com/watch?v=6qSurkv7NNM",
    "338": "https://www.youtube.com/watch?v=SuB1C8QF8RM",
    "339": "https://www.youtube.com/watch?v=9VR9YnK2D04",
    "340": "https://www.youtube.com/watch?v=s0qMxW-q6BY",
    "341": "https://www.youtube.com/watch?v=aG7uBv3mnsg",
    "342": "https://www.youtube.com/watch?v=6nJvSdQk0es",
    "343": "https://www.youtube.com/watch?v=D60qJG7tseU",
    "344": "https://www.youtube.com/watch?v=y_tr7ucTMHY",
    "345": "https://www.youtube.com/watch?v=Xm1zBfeI-RY",
    "346": "https://www.youtube.com/watch?v=K0dtLwEBX3Q",
    "347": "https://www.youtube.com/watch?v=yRp9mr9TgcA",
    "348": "https://www.youtube.com/watch?v=On65YomkD4g",
    "349": "https://www.youtube.com/watch?v=cnHNKIuzMVk",
    "350": "https://www.youtube.com/watch?v=rYV_vBMei_A",
    "351": "https://www.youtube.com/watch?v=Qo1T9ZuepmY",
    "352": "https://www.youtube.com/watch?v=EeFroE51w8Y",
    "353": "https://www.youtube.com/watch?v=QTuACjQAEqQ",
    "354": "https://www.youtube.com/watch?v=pb4tGtxy9yE",
    "355": "https://www.youtube.com/watch?v=rL9g1Vr1jWs",
    "356": "https://www.youtube.com/watch?v=veBLWvLwvQ8",
    "357": "https://www.youtube.com/watch?v=Z6as5nyLYa8",
    "358": "https://www.youtube.com/watch?v=PJlt94VhU_M",
    "359": "https://www.youtube.com/watch?v=-p9a4BxDUdE",
    "360": "https://www.youtube.com/watch?v=lUaHAM1HZdQ",
    "361": "https://www.youtube.com/watch?v=DCRsK6diXAE",
    "362": "https://www.youtube.com/watch?v=7M1qS8d9a8E",
    "363": "https://www.youtube.com/watch?v=xp-d4CRRylI",
    "364": "https://www.youtube.com/watch?v=D7NLGP2-GLc",
    "365": "https://www.youtube.com/watch?v=p9DHQ5v2LgE",
    "366": "https://www.youtube.com/watch?v=SnSVCN7Vuzk",
    "367": "https://www.youtube.com/watch?v=FkaoRqCR1Qc",
    "368": "https://www.youtube.com/watch?v=fk-hDs89Z8I",
    "369": "https://www.youtube.com/watch?v=9eU0EyNyVNk",
    "370": "https://www.youtube.com/watch?v=WW-CwdrG7Zo",
    "371": "https://www.youtube.com/watch?v=9eUp7OZe4NA",
    "372": "https://www.youtube.com/watch?v=20rnfeAocEo",
    "373": "https://www.youtube.com/watch?v=2Os83OCiqo4",
    "374": "https://www.youtube.com/watch?v=dtSsQXZeSqQ",
    "375": "https://www.youtube.com/watch?v=EyOkqnp-boI",
    "376": "https://www.youtube.com/watch?v=iHocK6sFQG4",
    "377": "https://www.youtube.com/watch?v=-pYZX4k5weo",
    "378": "https://www.youtube.com/watch?v=8S4HBQ8vSKY",
    "379": "https://www.youtube.com/watch?v=_g7rOev2ybA",
    "380": "https://www.youtube.com/watch?v=hfvTjhIT-DQ",
    "381": "https://www.youtube.com/watch?v=yEIIRYcw480",
    "382": "https://www.youtube.com/watch?v=zdqCReoBjNA",
    "383": "https://www.youtube.com/watch?v=_Y7x4rwunTM",
    "384": "https://www.youtube.com/watch?v=kcyghSL8dwc",
    "385": "https://www.youtube.com/watch?v=wScrNQt-IhU",
    "386": "https://www.youtube.com/watch?v=Z4MGD-mnSHo",
    "387": "https://www.youtube.com/watch?v=MSXFfVqU2Rk",
    "388": "https://www.youtube.com/watch?v=-cigdfK-ktk",
    "389": "https://www.youtube.com/watch?v=3JfsZZoCK-I",
    "390": "https://www.youtube.com/watch?v=6r_JxU0owC8",
    "391": "https://www.youtube.com/watch?v=4CfXjMoe2fA",
    "392": "https://www.youtube.com/watch?v=WZ0HCgbQ01Y",
    "393": "https://www.youtube.com/watch?v=rzb8Y3fZ7Uw",
    "394": "https://www.youtube.com/watch?v=k6Am9NI-3q0",
    "395": "https://www.youtube.com/watch?v=8N1zAktFoA0",
    "396": "https://www.youtube.com/watch?v=DNfjGf8qDWo",
    "397": "https://www.youtube.com/watch?v=AFnJNK48Iv0",
    "398": "https://www.youtube.com/watch?v=VHhO_p0Gzyo",
    "399": "https://www.youtube.com/watch?v=9tzUlynVPgA",
    "400": "https://www.youtube.com/watch?v=Pl6dhdohExc",
    "401": "https://www.youtube.com/watch?v=Dg2XiFULn3Q",
    "402": "https://www.youtube.com/watch?v=dwzZKr4SKHY",
    "403": "https://www.youtube.com/watch?v=4ol-obmlzBU",
    "404": "https://www.youtube.com/watch?v=Av4LvfAjdXg",
    "405": "https://www.youtube.com/watch?v=SmRxjG7xW58",
    "406": "https://www.youtube.com/watch?v=fLiSJdTA5Vk",
    "407": "https://www.youtube.com/watch?v=mekkPPhTwUc",
    "408": "https://www.youtube.com/watch?v=UiDXm0Y1CfI",
    "409": "https://www.youtube.com/watch?v=qUFlef2oVRM",
    "410": "https://www.youtube.com/watch?v=rR3jNanhKwk",
    "411": "https://www.youtube.com/watch?v=rioiyg_5IMs",
    "412": "https://www.youtube.com/watch?v=GU587FZB_gk",
    "413": "https://www.youtube.com/watch?v=7ApmhZKVsXM",
    "414": "https://www.youtube.com/watch?v=L-F7Sp7UcOk",
    "415": "https://www.youtube.com/watch?v=HkgZhA4sbic",
    "416": "https://www.youtube.com/watch?v=BRdz-QVlbKI",
    "417": "https://www.youtube.com/watch?v=RGeooJu7TUw",
    "418": "https://www.youtube.com/watch?v=iB5SSn4k-WM",
    "419": "https://www.youtube.com/watch?v=dHXwemIP94U",
    "420": "https://www.youtube.com/watch?v=Ty7iOct_PI8",
    "421": "https://www.youtube.com/watch?v=5EQpR-6uEcU",
    "422": "https://www.youtube.com/watch?v=W54JbWI39UQ",
    "423": "https://www.youtube.com/watch?v=kyG5DTHJRn4",
    "424": "https://www.youtube.com/watch?v=a0liyVeKGDg",
    "425": "https://www.youtube.com/watch?v=9xNmt3L6D5U",
    "426": "https://www.youtube.com/watch?v=70R4mbhB-y4",
    "427": "https://www.youtube.com/watch?v=LCkv535v4Ok",
    "428": "https://www.youtube.com/watch?v=pJtick2YMPs",
    "429": "https://www.youtube.com/watch?v=xXaDj2PGEDs",
    "430": "https://www.youtube.com/watch?v=37DO5uB7IOQ",
    "431": "https://www.youtube.com/watch?v=DmKmlupo91M",
    "432": "https://www.youtube.com/watch?v=SFDn0TVl730",
    "433": "https://www.youtube.com/watch?v=yuVlG81PVDo",
    "434": "https://www.youtube.com/watch?v=M7kip2r_8Tk",
    "435": "https://www.youtube.com/watch?v=wJQ3LvUaMds",
    "436": "https://www.youtube.com/watch?v=DHokCgyDV-0",
    "437": "https://www.youtube.com/watch?v=cmb52hp8Ud4",
    "438": "https://www.youtube.com/watch?v=AQMm1y35sXM",
    "439": "https://www.youtube.com/watch?v=aMEZCGynCn0",
    "440": "https://www.youtube.com/watch?v=VuxpSoj5eGA",
    "441": "https://www.youtube.com/watch?v=U4ym16En8xc",
    "442": "https://www.youtube.com/watch?v=CuF-oo0p7Es",
    "443": "https://www.youtube.com/watch?v=qg-7IQvW8Lg",
    "444": "https://www.youtube.com/watch?v=VjksTL6-lQs",
    "445": "https://www.youtube.com/watch?v=OMtRXZcDzbo",
    "446": "https://www.youtube.com/watch?v=lEvc-Vmcyyc",
    "447": "https://www.youtube.com/watch?v=3_kr1ba7voQ",
    "448": "https://www.youtube.com/watch?v=wHq55SJU4ZE",
    "449": "https://www.youtube.com/watch?v=9g089j2I4Fs",
    "450": "https://www.youtube.com/watch?v=mMZfaASuBbI",
    "451": "https://www.youtube.com/watch?v=SRcgXW3fg7I",
    "452": "https://www.youtube.com/watch?v=e4FoHTZzNrQ",
    "453": "https://www.youtube.com/watch?v=EOn959r8A4k",
    "454": "https://www.youtube.com/watch?v=16KaC4dDaeE",
    "455": "https://www.youtube.com/watch?v=F6QAsBXj284",
    "456": "https://www.youtube.com/watch?v=PE-O2EmOUkk",
    "457": "https://www.youtube.com/watch?v=mODTk_0iNWE",
    "458": "https://www.youtube.com/watch?v=wH6SLP6wEMY",
    "459": "https://www.youtube.com/watch?v=00FyQOvinS4",
    "460": "https://www.youtube.com/watch?v=v4FahDb_EuM",
    "461": "https://www.youtube.com/watch?v=BkwPPB2tjOI",
    "462": "https://www.youtube.com/watch?v=7GMgx-h-vCw",
    "463": "https://www.youtube.com/watch?v=2Ms2z4tj1EU",
    "464": "https://www.youtube.com/watch?v=c9JfsHZ5Ark",
    "465": "https://www.youtube.com/watch?v=uZ2pD2W0DXM",
    "466": "https://www.youtube.com/watch?v=2wem-qNP3yg",
    "467": "https://www.youtube.com/watch?v=PHRLFJoaIXQ",
    "468": "https://www.youtube.com/watch?v=pmHkUUEsbPM",
    "469": "https://www.youtube.com/watch?v=3AFtQj-ZbXU",
    "470": "https://www.youtube.com/watch?v=GAEJzMMk2WQ",
    "471": "https://www.youtube.com/watch?v=0doKHQReQH4",
    "472": "https://www.youtube.com/watch?v=TmkQmQ04aQk",
    "473": "https://www.youtube.com/watch?v=3eJVVZc_Dss",
    "474": "https://www.youtube.com/watch?v=JgMloBodNr0",
    "475": "https://www.youtube.com/watch?v=7Kszrnmsozg",
    "476": "https://www.youtube.com/watch?v=varJ50douf4",
    "477": "https://www.youtube.com/watch?v=4zeJehRh790",
    "478": "https://www.youtube.com/watch?v=49eMmsTDmgQ",
    "479": "https://www.youtube.com/watch?v=1p34cF7xJo0",
    "480": "https://www.youtube.com/watch?v=COAEdwOHpn0",
    "481": "https://www.youtube.com/watch?v=x7wEQ7q-_xM",
    "482": "https://www.youtube.com/watch?v=kn0zFi5orMU",
    "483": "https://www.youtube.com/watch?v=US64k5we5s0",
    "484": "https://www.youtube.com/watch?v=e6n44rxIuME",
    "485": "https://www.youtube.com/watch?v=_o3lA-GuZdI",
    "486": "https://www.youtube.com/watch?v=EmNa2mC1REU",
    "487": "https://www.youtube.com/watch?v=szamXjWAEso",
    "488": "https://www.youtube.com/watch?v=_xNrYww0OBY",
    "489": "https://www.youtube.com/watch?v=jAxb3hDo4x8",
    "490": "https://www.youtube.com/watch?v=8A0dsuOgLyg",
    "491": "https://www.youtube.com/watch?v=Co7KPOxg-5k",
    "492": "https://www.youtube.com/watch?v=V4Ve-KPG6mQ",
    "493": "https://www.youtube.com/watch?v=ddjCguUcCU4",
    "494": "https://www.youtube.com/watch?v=ILf6xg2sqhQ",
    "495": "https://www.youtube.com/watch?v=yqvOpAcE_EE",
    "496": "https://www.youtube.com/watch?v=iAAbWePVmEo",
    "497": "https://www.youtube.com/watch?v=0d0q6B-BuUA",
    "498": "https://www.youtube.com/watch?v=OV4K75Rb-OI",
    "499": "https://www.youtube.com/watch?v=FZPXeVnQqYs",
    "500": "https://www.youtube.com/watch?v=Ua3zsO9-2X8",
    "501": "https://www.youtube.com/watch?v=FlHMYuWZK0g",
    "502": "https://www.youtube.com/watch?v=RduBykShWsE",
    "503": "https://www.youtube.com/watch?v=uGY2V-go_x4",
    "504": "https://www.youtube.com/watch?v=JKzMvlzTQIs",
    "505": "https://www.youtube.com/watch?v=D_tT_5jcnU0",
    "506": "https://www.youtube.com/watch?v=6X1wkIN-Cis",
    "507": "https://www.youtube.com/watch?v=kaM0Z4YIuTo",
    "508": "https://www.youtube.com/watch?v=19pEqRVMq-I",
    "509": "https://www.youtube.com/watch?v=MVST2oE5nBE",
    "510": "https://www.youtube.com/watch?v=X8hHMFhz2Pc",
    "511": "https://www.youtube.com/watch?v=-3419VrV8Vk",
    "512": "https://www.youtube.com/watch?v=geb2ugQWBis",
    "513": "https://www.youtube.com/watch?v=elh4QZ-Fij4",
    "514": "https://www.youtube.com/watch?v=2w8AGdqCM0s",
    "515": "https://www.youtube.com/watch?v=wXIENxBI5mA",
    "516": "https://www.youtube.com/watch?v=HjTn64jPYYQ",
    "517": "https://www.youtube.com/watch?v=mg2bP7sg-QM",
    "518": "https://www.youtube.com/watch?v=444SonCfdPE",
    "519": "https://www.youtube.com/watch?v=ojukNBX0xRs",
    "520": "https://www.youtube.com/watch?v=GqqgbpjsANo",
    "521": "https://www.youtube.com/watch?v=97vtuS9WXZc",
    "522": "https://www.youtube.com/watch?v=cjw0Xd-BcIg",
    "523": "https://www.youtube.com/watch?v=7lR9ngghlhs",
    "524": "https://www.youtube.com/watch?v=qQz-1FXuAmk",
    "525": "https://www.youtube.com/watch?v=fm8Jh_12bGs",
    "526": "https://www.youtube.com/watch?v=yFMFvbRS0Mw",
    "527": "https://www.youtube.com/watch?v=h2_xAmV7XqA",
    "528": "https://www.youtube.com/watch?v=vh79qX7CK0c",
    "529": "https://www.youtube.com/watch?v=Kzc35-5a-W0",
    "530": "https://www.youtube.com/watch?v=z_ULuJComU8",
    "531": "https://www.youtube.com/watch?v=Rb5zqe-xg7s",
    "532": "https://www.youtube.com/watch?v=hWX79JHd_Sk",
    "533": "https://www.youtube.com/watch?v=g9Y0GTrC8Yk",
    "534": "https://www.youtube.com/watch?v=be6uoFLAuCE",
    "535": "https://www.youtube.com/watch?v=wSoey4BKe1Y",
    "536": "https://www.youtube.com/watch?v=YHfVrIMkgYg",
    "537": "https://www.youtube.com/watch?v=QSFP2EvOtk8",
    "538": "https://www.youtube.com/watch?v=kRjHUS_Ix4s",
    "539": "https://www.youtube.com/watch?v=r3pH5zs7aeY",
    "540": "https://www.youtube.com/watch?v=EfwQIFIdlWQ",
    "541": "https://www.youtube.com/watch?v=OTYzVyXbdKw",
    "542": "https://www.youtube.com/watch?v=_6a8tqjCZ3w",
    "543": "https://www.youtube.com/watch?v=_9TmgYS-BsU",
    "544": "https://www.youtube.com/watch?v=NLwqMcTD8lU",
    "545": "https://www.youtube.com/watch?v=I1D2ayYAKL0",
    "546": "https://www.youtube.com/watch?v=u9tMVmwsn2w",
    "547": "https://www.youtube.com/watch?v=iTfgnKEIbXM",
    "548": "https://www.youtube.com/watch?v=A6KuXacY6MU",
    "549": "https://www.youtube.com/watch?v=rQQEt6UslBI",
    "550": "https://www.youtube.com/watch?v=Qt4e8OzK9k0",
    "551": "https://www.youtube.com/watch?v=Wn5nj616hNI",
    "552": "https://www.youtube.com/watch?v=uMw9alCBJGg",
    "553": "https://www.youtube.com/watch?v=SjB4E02wpRM",
    "554": "https://www.youtube.com/watch?v=Xlva_BqXBgk",
    "555": "https://www.youtube.com/watch?v=OesQovAZ38Y",
    "556": "https://www.youtube.com/watch?v=TqM_jI_P2pI",
    "557": "https://www.youtube.com/watch?v=G2fo6bPBLxU",
    "558": "https://www.youtube.com/watch?v=9w4e6ncQG6U",
    "559": "https://www.youtube.com/watch?v=pzA0pwlEP_s",
    "560": "https://www.youtube.com/watch?v=tDUVFIYYClg",
    "561": "https://www.youtube.com/watch?v=7PCyZUfniNI",
    "562": "https://www.youtube.com/watch?v=RIcHuu1eM00",
    "563": "https://www.youtube.com/watch?v=KstVYG1eZLo",
    "564": "https://www.youtube.com/watch?v=WcbKoNxbg6E",
    "565": "https://www.youtube.com/watch?v=5fH_OdoULJ8",
    "566": "https://www.youtube.com/watch?v=gHgPE5cBZsk",
    "567": "https://www.youtube.com/watch?v=-O3V4eXegCA",
    "568": "https://www.youtube.com/watch?v=c5rmDJAwbmo",
    "569": "https://www.youtube.com/watch?v=h3Pn338Jbkc",
    "570": "https://www.youtube.com/watch?v=DU-gqqyFXhQ",
    "571": "https://www.youtube.com/watch?v=9MI2kh8VZFM",
    "572": "https://www.youtube.com/watch?v=6XKBBbizSwU",
    "573": "https://www.youtube.com/watch?v=IBj_6ya7xas",
    "574": "https://www.youtube.com/watch?v=M4e58v4OYAk",
    "575": "https://www.youtube.com/watch?v=Pl5UNPjWuQc",
    "576": "https://www.youtube.com/watch?v=Mo9jmUk1geA",
    "577": "https://www.youtube.com/watch?v=qNSke7mqfpU",
    "578": "https://www.youtube.com/watch?v=x7PXEUXWd_c",
    "579": "https://www.youtube.com/watch?v=ruwejYHFrso",
    "580": "https://www.youtube.com/watch?v=DM6XV-Xa-Q8",
    "581": "https://www.youtube.com/watch?v=XlKHkTRrxdY",
    "582": "https://www.youtube.com/watch?v=DdIqNGYts1M",
    "583": "https://www.youtube.com/watch?v=mCDRltoQyRU",
    "584": "https://www.youtube.com/watch?v=x21h3AlUjTk",
    "585": "https://www.youtube.com/watch?v=lBRMAtNr-F8",
    "586": "https://www.youtube.com/watch?v=nw9MZZ4yXhg",
    "587_a": "https://www.youtube.com/watch?v=0Lps7KHmebA",
    "587_b": "https://www.youtube.com/watch?v=GP8qu83lWls",
    "588": "https://www.youtube.com/watch?v=YfhkVkDCUzA",
    "589": "https://www.youtube.com/watch?v=KC11ybPhXuk",
    "590": "https://www.youtube.com/watch?v=TwLx_8N9Rh8",
    "591": "https://www.youtube.com/watch?v=aJ39JaQeOa4",
    "592": "https://www.youtube.com/watch?v=fiUau4pkV9Q",
    "593": "https://www.youtube.com/watch?v=qz4_paWtw8g",
    "594": "https://www.youtube.com/watch?v=fluE6tBTu6M",
    "595": "https://www.youtube.com/watch?v=sRZHnhpdE10",
    "596": "https://www.youtube.com/watch?v=e9GVzfcn-n8",
    "597": "https://www.youtube.com/watch?v=HNp73M6vd5o",
    "598": "https://www.youtube.com/watch?v=jsAz9HOKXjU",
    "599": "https://www.youtube.com/watch?v=hbDJN08OQ6I",
    "600": "https://www.youtube.com/watch?v=hER6dGJKpqY"
}

# got from https://stackoverflow.com/a/44352931
def resource_path(relative_path):
    import sys
    """ Get absolute path to resource, works for dev and for PyInstaller """
    base_path = getattr(sys, '_MEIPASS', os.path.dirname(os.path.abspath(__file__)))
    return os.path.join(base_path, relative_path)

def satcalc(ftoday,fweekday):
    import datetime
    if fweekday == 6:
        saturday = datetime.datetime.strftime(ftoday + datetime.timedelta(days=12-datetime.datetime.weekday(ftoday)), '%d-%m-%Y')  
    else:
        saturday = datetime.datetime.strftime(ftoday + datetime.timedelta(days=5-datetime.datetime.weekday(ftoday)), '%d-%m-%Y')
    
    return saturday

def link_ver(furl):
    import validators

    if validators.url(furl):
        return True
    else:
        return False

# got from https://stackoverflow.com/a/52664178
def number_get(Iurl):
    import urllib.request
    import json
    import urllib
    import validators
    from cleantext import clean


    params = {"format": "json", "url": "%s" % Iurl}
    url = "https://www.youtube.com/oembed"
    query_string = urllib.parse.urlencode(params)
    url = url + "?" + query_string

    if link_ver(Iurl):
        with urllib.request.urlopen(url) as response:
            response_text = response.read()
            data = json.loads(response_text.decode())
            title = clean(data['title'], no_emoji=True)
    else:
        title = Iurl
    
    # got from https://stackoverflow.com/a/4510805
    for i, c in enumerate(title):
        if c.isdigit():
            title = title[i:i+3]
            break

    return title

def file_writing(batfile,txtfile,frows,fdic,fmaindir,fcreds):
    if fdic[f'{frows[1]}'][1] == 0:
        print(f'Starting {frows[1]}')
        batfile.write(f'start https://www.google.com/search?q={fdic[f"{frows[1]}"][0]}\n')
        txtfile.write(f'{frows[1]}\n')
        if frows[1] != 'Anúncios':
        # Link hinos (should not be broken)
            for i in range(2,4):
                if link_ver(frows[i]):
                    batfile.write(f'start {frows[i]}\n')
                else:
                    batfile.write(f'start {hymndic[frows[i]]}\n')

            # Numero hinos
            txtfile.write(f'{number_get(frows[2])}\n{number_get(frows[3])}\n\n')

        if frows[1] == 'Culto' or frows[1] == 'Escola Sabatina' or frows[1] == 'Programa da Tarde':
            # Programas
            if frows[1] != 'Culto':
                txtfile.write(f'{frows[5]}\n')       
            # Doxologia
            elif frows[1] == 'Culto':
                batfile.write(f'start https://www.youtube.com/playlist?list=PL3sgRPOFYAyxahQy75UOv_wGlAvegskT_\n')
                for j in range(7,10):
                    if frows[j] != 'Normal':
                        if link_ver(frows[j]):
                            batfile.write(f'start {frows[j]}\n')
                        else:
                            batfile.write(f'start {hymndic[frows[j]]}\n')
                        txtfile.write(f'{number_get(frows[j])}\n')
                    else:
                        txtfile.write(f'{frows[j]}\n')
                txtfile.write('\n')
        try:
            # Ficheiros Necessários
            if frows[4] != '':
                txtfile.write(f'{necfiles(frows[4],fmaindir,fcreds)}\n\n')
            else:
                txtfile.write('\n')
        except IndexError:
            pass

        fdic[f'{frows[1]}'][1] += 1
        print()

def necfiles(dlink,fmaindir,fcreds):
    """Shows basic usage of the Drive v3 API.
    Prints the names and ids of the first 10 files the user has access to.
    """
    try:
        service = build('drive', 'v3', credentials=fcreds, static_discovery=False)

        # Call the Drive v3 API
        results = service.files().list(
            q = '"174Gu0skBr3sVf9pxwcXPg9R6FVlaOPBor_6-NuOWIcC8bcPYsVsQc-vSeszOrpkAQ-KftNTx" in parents and trashed = false', pageSize=1000, fields="nextPageToken, files(id, name)").execute()
        items = results.get('files', [])

        if not items:
            print('No files found.')
            return
        
        for item in items:
            if dlink[33:] == item['id']:
                request = service.files().get_media(fileId=item['id'])

                file = io.FileIO(fmaindir + "\\" + item['name'],'w')
                downloader = MediaIoBaseDownload(file, request)
                done = False
                print(f'Downloading {item["name"]} 0%.')
                while done is False:
                    status, done = downloader.next_chunk()
                    print(f'Downloading {item["name"]} {int(status.progress() * 100)}%.')         
                return item['name']

    except HttpError as error:
        # TODO(developer) - Handle errors from drive API.
        print(f'An error occurred: {error}')
